package fr.formation.inti.entities;
// Generated 5 ao�t 2019 15:42:24 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "bd")
public class Department implements java.io.Serializable {

	private Integer deptId;
	private String name;
	private Set<Employee> employees = new HashSet<Employee>(0);
	private Set<Employee> employees_1 = new HashSet<Employee>(0);

	public Department() {
	}

	public Department(String name) {
		this.name = name;
	}

	public Department(String name, Set<Employee> employees, Set<Employee> employees_1) {
		this.name = name;
		this.employees = employees;
		this.employees_1 = employees_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DEPT_ID", unique = true, nullable = false)
	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	@Column(name = "NAME", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Employee> getEmployees_1() {
		return this.employees_1;
	}

	public void setEmployees_1(Set<Employee> employees_1) {
		this.employees_1 = employees_1;
	}

	@Override
	public String toString() {
		return "Department [deptId=" + deptId + ", name=" + name + "]";
	}

}
